/* recomp.h — the runtime the lifter's C is written against.
 *
 * The guest is a 32-bit x86 process: eight general registers, eight XMM
 * registers, EFLAGS, and a flat 4 GiB address space. The address space is one
 * host reservation, `mem`, and a guest pointer p is the host byte mem + p —
 * the same shape N64Recomp gives its RDRAM. Nothing is relocated: the image
 * sits at its preferred base inside the reservation.
 *
 * A lifted function is `void f_<va>(cpu_t *c)`. It keeps the registers in C
 * locals while it runs and writes them back to `c` around every call out and
 * at its `ret`, so a caller and a callee agree through `c` and through the
 * guest stack in `mem`, exactly as the original's do through the CPU. The
 * return address is still pushed and popped: `ret` leaves it in `c->eip`,
 * and the caller checks it is the one it pushed.
 *
 * Floating point is modelled as SSE: the executable's own float code is
 * SSE2 (docs/lab/RECOMP-REVIEW.md, "What changed our understanding", counts
 * its x87 at about 700 hits against 12,500 `movss`, most of them in the C
 * runtime's own paths). Every SSE arithmetic result is IEEE-754 on both
 * sides — the lifter emits one C operation per guest operation, compiled
 * with -ffp-contract=off — and where x86 and AArch64 disagree the helpers
 * below say it in x86's terms: which NaN comes out, min/max operand order,
 * and what an out-of-range truncation returns. No x87 instruction is
 * lifted; one stops the lift and names itself.
 */
#ifndef RECOMP_H
#define RECOMP_H

#include <stdint.h>
#include <string.h>

typedef struct { uint32_t d[4]; } x128;

typedef struct cpu {
    uint32_t eax, ecx, edx, ebx, esp, ebp, esi, edi;
    uint32_t eip;          /* the return address the last `ret` popped */
    uint32_t cf, pf, af, zf, sf, of, df;
    x128 xmm[8];
    uint32_t mxcsr;
    uint32_t fs_base;      /* the guest TIB */
    uint64_t tsc;
    uint8_t *mem;
} cpu_t;

/* ---- memory: a guest address is an offset into the reservation ---- */
static inline uint32_t ld8(uint8_t *m, uint32_t a) { return m[a]; }
static inline uint32_t ld16(uint8_t *m, uint32_t a) { uint16_t v; memcpy(&v, m + a, 2); return v; }
static inline uint32_t ld32(uint8_t *m, uint32_t a) { uint32_t v; memcpy(&v, m + a, 4); return v; }
static inline uint64_t ld64(uint8_t *m, uint32_t a) { uint64_t v; memcpy(&v, m + a, 8); return v; }
static inline x128 ld128(uint8_t *m, uint32_t a) { x128 v; memcpy(&v, m + a, 16); return v; }
static inline void st8(uint8_t *m, uint32_t a, uint32_t v) { m[a] = (uint8_t)v; }
static inline void st16(uint8_t *m, uint32_t a, uint32_t v) { uint16_t w = (uint16_t)v; memcpy(m + a, &w, 2); }
static inline void st32(uint8_t *m, uint32_t a, uint32_t v) { memcpy(m + a, &v, 4); }
static inline void st64(uint8_t *m, uint32_t a, uint64_t v) { memcpy(m + a, &v, 8); }
static inline void st128(uint8_t *m, uint32_t a, x128 v) { memcpy(m + a, &v, 16); }

static inline uint32_t parity8(uint32_t v) { return !__builtin_parity(v & 0xff); }

/* ---- the runtime's entry points (runtime.c) ---- */
uint8_t *rc_reserve(void);                         /* the 4 GiB guest space, no access yet, or NULL */
int rc_map(uint8_t *mem, uint32_t base, uint32_t size);  /* open a range read-write; 0 on success */
int rc_call(cpu_t *c, uint32_t entry);             /* 0, or 1 and rc_trap_message() says why */
const char *rc_trap_message(void);
_Noreturn void rc_trap(cpu_t *c, uint32_t at, const char *why);
_Noreturn void rc_badret(cpu_t *c, uint32_t at, uint32_t want);
void rc_cpuid(cpu_t *c);

/* ---- generated by lift.py (lifted.c) ---- */
void rc_dispatch(cpu_t *c, uint32_t target);       /* an indirect call or jump */
extern const uint32_t rc_lifted_n;                 /* the lifted functions' entries */
extern const uint32_t rc_lifted[];

/* ---- SSE scalar semantics, x86's ---- */
static inline float f32(uint32_t u) { float f; memcpy(&f, &u, 4); return f; }
static inline uint32_t u32f(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }
static inline double f64(uint64_t u) { double f; memcpy(&f, &u, 8); return f; }
static inline uint64_t u64d(double f) { uint64_t u; memcpy(&u, &f, 8); return u; }
static inline uint64_t lane64(x128 x, int i) { return (uint64_t)x.d[2 * i] | (uint64_t)x.d[2 * i + 1] << 32; }
static inline void setlane64(x128 *x, int i, uint64_t v) { x->d[2 * i] = (uint32_t)v; x->d[2 * i + 1] = (uint32_t)(v >> 32); }

static inline int nan32(uint32_t u) { return (u & 0x7fffffff) > 0x7f800000; }
static inline int nan64(uint64_t u) { return (u & 0x7fffffffffffffffull) > 0x7ff0000000000000ull; }

/* x86: a NaN operand wins, the first before the second, quieted; an invalid
 * operation with no NaN in gives the negative default NaN. AArch64 prefers a
 * signalling second operand and gives a positive default NaN; the fix-up
 * runs only when the result is a NaN. */
static inline uint32_t fix32(uint32_t r, uint32_t a, uint32_t b) {
    if (__builtin_expect(nan32(r), 0)) {
        if (nan32(a)) return a | 0x00400000u;
        if (nan32(b)) return b | 0x00400000u;
        return 0xffc00000u;
    }
    return r;
}
static inline uint64_t fix64(uint64_t r, uint64_t a, uint64_t b) {
    if (__builtin_expect(nan64(r), 0)) {
        if (nan64(a)) return a | 0x0008000000000000ull;
        if (nan64(b)) return b | 0x0008000000000000ull;
        return 0xfff8000000000000ull;
    }
    return r;
}
static inline uint32_t ss_add(uint32_t a, uint32_t b) { return fix32(u32f(f32(a) + f32(b)), a, b); }
static inline uint32_t ss_sub(uint32_t a, uint32_t b) { return fix32(u32f(f32(a) - f32(b)), a, b); }
static inline uint32_t ss_mul(uint32_t a, uint32_t b) { return fix32(u32f(f32(a) * f32(b)), a, b); }
static inline uint32_t ss_div(uint32_t a, uint32_t b) { return fix32(u32f(f32(a) / f32(b)), a, b); }
static inline uint32_t ss_sqrt(uint32_t b) { return fix32(u32f(__builtin_sqrtf(f32(b))), b, b); }
/* min/max answer the second operand when either is a NaN or both are zero */
static inline uint32_t ss_min(uint32_t a, uint32_t b) { return f32(a) < f32(b) ? a : b; }
static inline uint32_t ss_max(uint32_t a, uint32_t b) { return f32(a) > f32(b) ? a : b; }
static inline uint64_t sd_add(uint64_t a, uint64_t b) { return fix64(u64d(f64(a) + f64(b)), a, b); }
static inline uint64_t sd_sub(uint64_t a, uint64_t b) { return fix64(u64d(f64(a) - f64(b)), a, b); }
static inline uint64_t sd_mul(uint64_t a, uint64_t b) { return fix64(u64d(f64(a) * f64(b)), a, b); }
static inline uint64_t sd_div(uint64_t a, uint64_t b) { return fix64(u64d(f64(a) / f64(b)), a, b); }
static inline uint64_t sd_sqrt(uint64_t b) { return fix64(u64d(__builtin_sqrt(f64(b))), b, b); }
static inline uint64_t sd_min(uint64_t a, uint64_t b) { return f64(a) < f64(b) ? a : b; }
static inline uint64_t sd_max(uint64_t a, uint64_t b) { return f64(a) > f64(b) ? a : b; }

/* conversions: out of range or NaN gives the integer indefinite 0x80000000;
 * the rounding forms round to nearest-even (MXCSR's default, and FPCR's). */
static inline uint32_t cvtt_ss(uint32_t a) {
    float f = f32(a);
    return (f >= -2147483648.0f && f < 2147483648.0f) ? (uint32_t)(int32_t)f : 0x80000000u;
}
static inline uint32_t cvt_ss(uint32_t a) { return cvtt_ss(u32f(__builtin_rintf(f32(a)))); }
static inline uint32_t cvtt_sd(uint64_t a) {
    double f = f64(a);
    return (f > -2147483649.0 && f < 2147483648.0) ? (uint32_t)(int32_t)f : 0x80000000u;
}
static inline uint32_t cvt_sd(uint64_t a) { return cvtt_sd(u64d(__builtin_rint(f64(a)))); }
/* float<->double: both ISAs quiet a NaN and keep the top of its payload */
static inline uint64_t cvt_ss_sd(uint32_t a) { return u64d((double)f32(a)); }
static inline uint32_t cvt_sd_ss(uint64_t a) { return u32f((float)f64(a)); }
static inline uint32_t cvt_si_ss(uint32_t a) { return u32f((float)(int32_t)a); }
static inline uint64_t cvt_si_sd(uint32_t a) { return u64d((double)(int32_t)a); }

/* compare predicates (cmpss/cmpps imm8 0..7) */
static inline int cmp_pred32(uint32_t a, uint32_t b, int p) {
    float x = f32(a), y = f32(b); int un = nan32(a) || nan32(b);
    switch (p & 7) {
    case 0: return !un && x == y; case 1: return !un && x < y; case 2: return !un && x <= y;
    case 3: return un; case 4: return un || x != y; case 5: return un || !(x < y);
    case 6: return un || !(x <= y); default: return !un;
    }
}
static inline int cmp_pred64(uint64_t a, uint64_t b, int p) {
    double x = f64(a), y = f64(b); int un = nan64(a) || nan64(b);
    switch (p & 7) {
    case 0: return !un && x == y; case 1: return !un && x < y; case 2: return !un && x <= y;
    case 3: return un; case 4: return un || x != y; case 5: return un || !(x < y);
    case 6: return un || !(x <= y); default: return !un;
    }
}

#endif
