/* Uses an authored TLV fixture generated by test_search_graph.py. */
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
typedef unsigned char u8;
typedef unsigned int u32;
typedef int i32;
typedef void *HANDLE;
#define K_INFO 5
#define INVALID_HANDLE ((HANDLE)(intptr_t)-1)
#define GENERIC_WRITE 1
#define FILE_SHARE_READ 1
#define FILE_ATTRIBUTE_NORMAL 1
static HANDLE g_proc;
static i32 g_frame=223;
static u32 source[65536], result[65536], source_bytes, result_bytes;
static u32 reads, fail_at, short_read, success, failures, fail_create, fail_write, short_write;
static void emit(u32 k,u32 tag,u32 a,u32 b,u32 c,u32 d,u32 e) {
    (void)k;(void)a;(void)b;(void)c;(void)d;(void)e;
    if (tag==150) success++; else { assert(tag==151); failures++; }
}
static void flush(void) {}
static void path_join(char *out,const char *name) { strcpy(out,name); }
static HANDLE CreateFileA(const char *p,u32 a,u32 b,void *c,u32 d,u32 e,void *f) {
    (void)p;(void)a;(void)b;(void)c;(void)d;(void)e;(void)f; return fail_create?INVALID_HANDLE:(HANDLE)1;
}
static i32 WriteFile(HANDLE h,const void *p,u32 n,u32 *written,void *x) {
    (void)h;(void)x;assert(n<=sizeof result);memcpy(result,p,n);result_bytes=n;*written=short_write?n-1:n;return !fail_write;
}
static void CloseHandle(HANDLE h) {(void)h;}
static i32 ReadProcessMemory(HANDLE h,const void *pointer,void *out,u32 size,u32 *copied) {
    (void)h;u32 address=(u32)(uintptr_t)pointer; reads++;
    if (reads==fail_at) { *copied=short_read?size-1:0;return (i32)short_read; }
    for (u32 at=32;at<source_bytes;) {
        u32 *p=source+at/4,a=p[2],n=p[3];at+=16+n;
        if (address>=a && address+size<=a+n) {
            memcpy(out,(u8 *)(p+4)+address-a,size);*copied=size;return 1;
        }
    }
    *copied=0;return 0;
}
#include "live_search_graph.h"
static void reset(void) { reads=fail_at=short_read=success=failures=result_bytes=fail_create=fail_write=short_write=0; }
int main(int argc,char **argv) {
    assert(argc==3);FILE *f=fopen(argv[1],"rb");assert(f);
    source_bytes=(u32)fread(source,1,sizeof source,f);fclose(f);
    assert(source_bytes>=32 && source_bytes%4==0);
    reset();capture_search_graph(0x10000);
    assert(success==1 && !failures && result_bytes);u32 total=reads;
    f=fopen(argv[2],"wb");assert(f);assert(fwrite(result,1,result_bytes,f)==result_bytes);fclose(f);
    for (u32 partial=0;partial<2;partial++) for (u32 i=1;i<=total;i++) {
        reset();fail_at=i;short_read=partial;capture_search_graph(0x10000);
        assert(!success && failures && !result_bytes && reads==i);
    }
    /* Deliberately corrupt the first node's left link into a cycle. */
    for (u32 at=32;at<source_bytes;) {
        u32 *p=source+at/4;at+=16+p[3];
        if (p[0]==3 && p[1]==0) {
            u32 old=p[4];p[4]=p[2];reset();capture_search_graph(0x10000);
            assert(!success && failures);p[4]=old;break;
        }
    }
    for (u32 mode=0;mode<3;mode++) {
        reset();fail_create=mode==0;fail_write=mode==1;short_write=mode==2;
        capture_search_graph(0x10000);assert(!success && failures);
    }
    for (u32 at=32;at<source_bytes;) {
        u32 *p=source+at/4;at+=16+p[3];
        if (p[0]==2) {
            u32 old=p[6];p[6]=GRAPH_NODES+1;reset();capture_search_graph(0x10000);
            assert(!success && failures);p[6]=old;break;
        }
    }
    reset();graph_used=32;assert(!graph_record(1,0,0xfffffff0u,72) && failures && !reads);
    reset();graph_used=GRAPH_BYTES-4;assert(!graph_record(1,0,0x10104,72) && failures);
    reset();graph_payload_count=GRAPH_PAYLOADS;
    for(u32 i=0;i<GRAPH_PAYLOADS;i++) graph_payloads[i]=i+0x10000;
    assert(!graph_payload(0x90000) && failures);
    printf("graph collector: success, %u read refusals, cycle, capacity, pointer and file-write checks\n",2*total);
    return 0;
}
