#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["unicorn==2.1.4"]
# ///
"""sweep_world_space_at_corner.py — `WorldData::space_at_corner@006b27f0` under unicorn.

    uv run tools/emu/sweep_world_space_at_corner.py <install>/riseofnations.exe

One row per input, `<grid> <tx> <ty> <who> <junk> <need_city> -> <result>`:

    grid       which of twelve seeded tile grids is laid out (see below)
    tx, ty     the corner, as the values the two `TCoord*` arguments point at
               (read once each; the script maps two cells for them)
    who        the stack argument `param_3`: the leader the 4x4 is placed for
    junk       `param_4`, which the function never reads — any integer
    need_city  `param_5`; the function tests it `!= 0`, so 7 and -1 ride too

The function is `__thiscall` on a `WorldData` with five stack arguments, a
`ret 0x14`; it calls nothing and reads no global but its own `.rdata` tables
(`grid_index_x/y`, `grid_threes`, which the image supplies). This script lays
out the `WorldData` fields it reads (`xs` +0, `tile_xs` +0x18, `tile_ys` +0x1c,
`wdata` +0x134, `tdata` +0x138), a `tdata` array of ushort masks (tile_xs *
tile_ys) and a `wdata` array of 0x1c-byte cells (xs * ys) whose only read
field is the signed byte `who` at +0xf. Nothing is stood in for.

The grids are generated by an integer hash of (grid, x, y) that
`crates/sim/src/sweep/world_space_at_corner.rs` repeats exactly, so a row
need name only its grid: grid g is (4 + g%3) x (3 + g%2) cells (4 tiles to a
cell), each tile's mask a mix of the bits the function reads (`& 3`, 0x80,
0x100, 0x4000) at a density that rises with g, plus noise in the bits it does
not read; each cell's `who` is -1, -2 (the "ambiguous" word) or a player 0..2.
Corners run from five tiles off every edge through the map, with the
boundaries of every comparison (-1/0 and tile_xs-1/tile_xs, the first-four
early out), and a few huge ones (+/-2^30).
"""
import os
import random
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from callfn import Image, Machine, signed  # noqa: E402

ENTRY = 0x006B27F0
THIS, TX, TY = 0x10000000, 0x10001000, 0x10001004
TDATA, WDATA = 0x10100000, 0x10200000
M32 = 0xFFFFFFFF
GRIDS = 12
DENS = (0, 0, 1, 2, 3, 5, 8, 12, 20, 40, 80, 160)


def mix(a, b, c):
    h = (a * 0x9E3779B1 + (b & M32) * 0x85EBCA6B + (c & M32) * 0xC2B2AE35 + 0x27D4EB2F) & M32
    h ^= h >> 15
    h = (h * 0x2C1B3C6D) & M32
    h ^= h >> 12
    h = (h * 0x297A2D39) & M32
    h ^= h >> 15
    return h


def dims(g):
    return 4 + g % 3, 3 + g % 2


def tile_mask(g, x, y):
    d = DENS[g]
    city_off = (g * 37) % 96
    h1, h2 = mix(g, x, y), mix(g + 100, x, y)
    obj = 3 if ((h1 >> 2) & 255) < d else (h1 >> 10) % 3
    m = obj
    if ((h1 >> 18) & 255) < d:
        m |= 0x80
    if (h2 & 255) < d:
        m |= 0x4000
    if ((h2 >> 8) & 255) >= city_off:
        m |= 0x100
    return m | ((h2 >> 16) & 0xBE7C)


def cell_who(g, cx, cy):
    d = DENS[g]
    h3 = mix(g + 200, cx, cy)
    r = h3 & 255
    if r < d * 2:
        return (h3 >> 8) % 3
    return -2 if r < d * 2 + 8 else -1


def lay_out(m, g):
    xs, ys = dims(g)
    tw, th = xs * 4, ys * 4
    w = bytearray(0x170)
    struct.pack_into("<i", w, 0x0, xs)
    struct.pack_into("<i", w, 0x4, ys)
    struct.pack_into("<i", w, 0x18, tw)
    struct.pack_into("<i", w, 0x1C, th)
    struct.pack_into("<I", w, 0x134, WDATA)
    struct.pack_into("<I", w, 0x138, TDATA)
    m.uc.mem_write(THIS, bytes(w))
    m.uc.mem_write(TDATA, b"".join(struct.pack("<H", tile_mask(g, x, y))
                                   for y in range(th) for x in range(tw)))
    cells = bytearray(0x1C * xs * ys)
    for cy in range(ys):
        for cx in range(xs):
            cells[0x1C * (cy * xs + cx) + 0xF] = cell_who(g, cx, cy) & 0xFF
    m.uc.mem_write(WDATA, bytes(cells))


def rows():
    rng = random.Random(1619)
    out = []
    for g in range(GRIDS):
        xs, ys = dims(g)
        tw, th = xs * 4, ys * 4
        ex = (-4, -3, -1, 0, 1, tw - 5, tw - 4, tw - 3, tw - 1, tw)
        ey = (-4, -3, -1, 0, 1, th - 5, th - 4, th - 3, th - 1, th)
        for tx in ex:
            for ty in ey:
                out.append((g, tx, ty, rng.randint(0, 3), 0, 1 if rng.random() < .5 else 0))
        for _ in range(130):
            out.append((g, rng.randint(-5, tw + 4), rng.randint(-5, th + 4), rng.randint(0, 3),
                        rng.choice((0, rng.randint(-1000, 1000))), rng.choice((0, 1, 1, 7, -1))))
        for _ in range(130):  # inside the map, where the answers vary
            out.append((g, rng.randint(-1, tw - 3), rng.randint(-1, th - 3), rng.randint(0, 3),
                        rng.randint(-5, 5), rng.choice((0, 1))))
        for v in (1 << 30, -(1 << 30)):
            out.append((g, v, 2, 1, 0, 0))
            out.append((g, 2, v, 1, 0, 1))
    return out


def main(argv):
    m = Machine(Image(argv[1]))
    for a, n in ((THIS, 0x1000), (TX, 0x1000), (TDATA, 0x10000), (WDATA, 0x10000)):
        m.uc.mem_map(a, n)
    cur = None
    hist = {}
    for r in rows():
        g, tx, ty, who, junk, need = r
        if g != cur:
            lay_out(m, g)
            cur = g
        m.uc.mem_write(TX, struct.pack("<ii", tx, ty))
        res = signed(m.call(ENTRY, (TX, TY, who, junk, need), ecx=THIS))
        hist[res] = hist.get(res, 0) + 1
        print(" ".join(map(str, r)), "->", res)
    print("results:", dict(sorted(hist.items())), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
